#server:
#  port: 443
#  ssl:
#    key-store: certs/keystore.p12
#    key-store-password: changeit
#    keyStoreType: PKCS12
#    keyAlias: quick-start-springboot

spring:
  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

# Postgresql config
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver


management:
  endpoints:
    web:
      exposure:
        include: '*'