version: 2

jobs:
  build_jar:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: ./gradlew clean build
  build_docker:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: docker build -t nicolas2lee-tutorial/quick-start-java-springboot:latest . 
workflows:
  version: 2
  build:
    jobs:
      - build_jar
      - build_docker
