version: 2


jobs:
  build_jar:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew clean build
  build_docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - run: docker build -t nicolas2lee-tutorial/quick-start-java-springboot:latest .
workflows:
  version: 2
  build:
    jobs:
      - build_jar
      - build_docker
